def botSetup(ctrl) :
	motorIds = {}
	motorFactors = {}
	if(simulator) :
		# Leg 0
		motorIds[0] = 0
		motorFactors[0] = 1
		motorIds[1] = 1
		motorFactors[1] = 1
		motorIds[2] = 2
		motorFactors[2] = 1
		# Leg 1
		motorIds[3] = 15
		motorFactors[3] = 1
		motorIds[4] = 16
		motorFactors[4] = 1
		motorIds[5] = 17
		motorFactors[5] = 1
		# Leg 2
		motorIds[6] = 12
		motorFactors[6] = 1
		motorIds[7] = 13
		motorFactors[7] = 1
		motorIds[8] = 12
		motorFactors[8] = 1
		# Leg 3
		motorIds[9] = 9
		motorFactors[9] = 1
		motorIds[10] = 10
		motorFactors[10] = 1
		motorIds[11] = 11
		motorFactors[11] = 1
		# Leg 4
		motorIds[12] = 6
		motorFactors[12] = 1
		motorIds[13] = 7
		motorFactors[13] = 1
		motorIds[14] = 8
		motorFactors[14] = 1
		# Leg 5
		motorIds[15] = 3
		motorFactors[15] = 1
		motorIds[16] = 4
		motorFactors[16] = 1
		motorIds[17] = 5
		motorFactors[17] = 1
	else :
		# Leg 0
		motorIds[0] = 0
		motorFactors[0] = 1
		motorIds[1] = 2
		motorFactors[1] = 1
		motorIds[2] = 4
		motorFactors[2] = 1
		# Leg 1
		motorIds[3] = 12
		motorFactors[3] = -1
		motorIds[4] = 14
		motorFactors[4] = -1
		motorIds[5] = 16
		motorFactors[5] = -1
		# Leg 2
		motorIds[6] = 13
		motorFactors[6] = 1
		motorIds[7] = 15
		motorFactors[7] = 1
		motorIds[8] = 17
		motorFactors[8] = 1
		# Leg 3
		motorIds[9] = 7
		motorFactors[9] = 1
		motorIds[10] = 9
		motorFactors[10] = 1
		motorIds[11] = 11
		motorFactors[11] = 1
		# Leg 4
		motorIds[12] = 1
		motorFactors[12] = -1
		motorIds[13] = 3
		motorFactors[13] = -1
		motorIds[14] = 5
		motorFactors[14] = -1
		# Leg 5
		motorIds[15] = 6
		motorFactors[15] = -1
		motorIds[16] = 8
		motorFactors[16] = -1
		motorIds[17] = 10
		motorFactors[17] = -1

	# Calibration
	motorRefs = {}
	motorRefs[0] = motorIds[motorIds[0]].position;
	motorRefs[1] = motorIds[motorIds[1]].position;
	motorRefs[2] = motorIds[motorIds[2]].position;
	motorRefs[3] = motorIds[motorIds[3]].position;
	motorRefs[4] = motorIds[motorIds[4]].position;
	motorRefs[5] = motorIds[motorIds[5]].position;
	motorRefs[6] = motorIds[motorIds[6]].position;
	motorRefs[7] = motorIds[motorIds[7]].position;
	motorRefs[8] = motorIds[motorIds[8]].position;
	motorRefs[9] = motorIds[motorIds[9]].position;
	motorRefs[10] = motorIds[motorIds[10]].position;
	motorRefs[11] = motorIds[motorIds[11]].position;
	motorRefs[12] = motorIds[motorIds[12]].position;
	motorRefs[13] = motorIds[motorIds[13]].position;
	motorRefs[14] = motorIds[motorIds[14]].position;
	motorRefs[15] = motorIds[motorIds[15]].position;
	motorRefs[16] = motorIds[motorIds[16]].position;
	motorRefs[17] = motorIds[motorIds[17]].position;
	return (motorIds, motorFactors, motorRefs)